# Generated by Django 5.0.6 on 2024-06-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New Task', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='NewTask', max_length=20),
        ),
    ]
